name: "Top Congressional News"
# author: "MettaCode Developers"
# description: "Retrieve latest floor actions from US Congress and create JSON file"

on:
  push:
    branches:
      - main

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "*/30 * * * *"

permissions:
  contents: write

jobs:
  save_json_file:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14, 20]
    steps:
      - uses: actions/checkout@v4
      - run: node --version
      - run: npm install axios
      - run: npm install cheerio
      - name: run-javascript
        run: npm run get-news
        with:
          node-version: ${{ matrix.version }}
      - name: commit-top-news-json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Top News JSON Updated
